theme: jekyll-theme-architect

# Setup

name:        Gemini Bad

tagline:      For all your Gemini friends wait no Gemini should be your friend

locale:       "en"

title: Gemini's Are Terrible

description: Why the Gemini's are the spawns of satan
